In [1]:
# Importar librerias
import os
import pandas as pd
import numpy as np
from datetime import date

### 1. Tratamiento de datos de Ingresos

In [3]:
# Cargar datos de movimientos contables de ingresos
df_fact_mov_ingresos = pd.read_csv('fact_mov_ingresos.csv', sep=';')
# Visualizar resultados
df_fact_mov_ingresos

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,01/01/2023,2023,1,7,Ingreso,704000,Descuentos sobre ventas,29,11,-2743
1,01/01/2023,2023,1,7,Ingreso,705000,Prestaciones de servicios,46,6,12757
2,01/01/2023,2023,1,7,Ingreso,705000,Prestaciones de servicios,12,9,6585
3,01/01/2023,2023,1,7,Ingreso,704000,Descuentos sobre ventas,44,9,-1034
4,01/01/2023,2023,1,7,Ingreso,705000,Prestaciones de servicios,22,7,16624
...,...,...,...,...,...,...,...,...,...,...
22957,31/12/2025,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,11273
22958,31/12/2025,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,7350
22959,31/12/2025,2025,12,7,Ingreso,746000,Subvenciones para gastos de personal,0,0,15632
22960,31/12/2025,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,11285
22961,31/12/2025,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,12534

In [13]:
# Generar columna de presupuesto
df_fact_mov_ingresos['Importe_Presupuesto'] = (
    df_fact_mov_ingresos['Importe'] * 
    (1 + np.random.uniform(-0.05, 0.05, size=len(df_fact_mov_ingresos)))
)
# Redondear decimales
df_fact_mov_ingresos['Importe_Presupuesto'] = df_fact_mov_ingresos['Importe_Presupuesto'].round(0).astype(int)

# Eliminar columna "Importe"
df_fact_mov_ingresos.drop(columns=['Importe'], inplace=True)

# Renombrar nombre columna Importe_Presupuesto por Importe
df_fact_mov_ingresos = df_fact_mov_ingresos.rename(columns={'Importe_Presupuesto': 'Importe'})

# Visualizar resultados
df_fact_mov_ingresos

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,01/01/2023,2023,1,7,Ingreso,704000,Descuentos sobre ventas,29,11,-2826
1,01/01/2023,2023,1,7,Ingreso,705000,Prestaciones de servicios,46,6,12545
2,01/01/2023,2023,1,7,Ingreso,705000,Prestaciones de servicios,12,9,6483
3,01/01/2023,2023,1,7,Ingreso,704000,Descuentos sobre ventas,44,9,-1000
4,01/01/2023,2023,1,7,Ingreso,705000,Prestaciones de servicios,22,7,16655
...,...,...,...,...,...,...,...,...,...,...
22957,31/12/2025,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,10981
22958,31/12/2025,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,7440
22959,31/12/2025,2025,12,7,Ingreso,746000,Subvenciones para gastos de personal,0,0,15704
22960,31/12/2025,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,11821
22961,31/12/2025,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,12313

In [8]:
#df_fact_mov_ingresos.dtypes

In [14]:
# Exportar resultados a csv
df_fact_mov_ingresos.to_csv("PresupuestoVentas2025.csv", index=False)

### 2. Tratamiento de datos de Gastos

In [11]:
# Cargar datos de movimientos contables de gastos
df_fact_mov_gastos = pd.read_csv('fact_mov_gastos.csv', sep=';')
# Eliminar columnas innecesarias
df_fact_mov_gastos.drop(columns=['Unnamed: 0'], inplace=True)
# Visualizar resultados
df_fact_mov_gastos

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,01/01/2023,2023,1,6,Gasto,625000,Primas de seguros,0,0,-12007
1,01/01/2023,2023,1,6,Gasto,606000,Descuentos sobre compras,0,0,613
2,01/01/2023,2023,1,6,Gasto,600000,Compras de mercaderías,0,0,-11246
3,01/01/2023,2023,1,6,Gasto,627000,"Publicidad, propaganda y relaciones públicas",0,0,-7027
4,01/01/2023,2023,1,6,Gasto,601000,Compras de materias primas,0,0,-15960
...,...,...,...,...,...,...,...,...,...,...
15942,31/12/2025,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-19395
15943,31/12/2025,2025,12,6,Gasto,660000,Gastos financieros,0,0,-12510
15944,31/12/2025,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-4867
15945,31/12/2025,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-32824
15946,31/12/2025,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-24703

In [15]:
# Generar columna de presupuesto
df_fact_mov_gastos['Importe_Presupuesto'] = (
    df_fact_mov_gastos['Importe'] * 
    (1 + np.random.uniform(-0.05, 0.05, size=len(df_fact_mov_gastos)))
)
# Redondear decimales
df_fact_mov_gastos['Importe_Presupuesto'] = df_fact_mov_gastos['Importe_Presupuesto'].round(0).astype(int)

# Eliminar columna "Importe"
df_fact_mov_gastos.drop(columns=['Importe'], inplace=True)

# Renombrar nombre columna Importe_Presupuesto por Importe
df_fact_mov_gastos = df_fact_mov_gastos.rename(columns={'Importe_Presupuesto': 'Importe'})

# Visualizar resultados
df_fact_mov_gastos

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,01/01/2023,2023,1,6,Gasto,625000,Primas de seguros,0,0,-11674
1,01/01/2023,2023,1,6,Gasto,606000,Descuentos sobre compras,0,0,620
2,01/01/2023,2023,1,6,Gasto,600000,Compras de mercaderías,0,0,-11640
3,01/01/2023,2023,1,6,Gasto,627000,"Publicidad, propaganda y relaciones públicas",0,0,-6854
4,01/01/2023,2023,1,6,Gasto,601000,Compras de materias primas,0,0,-15286
...,...,...,...,...,...,...,...,...,...,...
15942,31/12/2025,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-18525
15943,31/12/2025,2025,12,6,Gasto,660000,Gastos financieros,0,0,-12498
15944,31/12/2025,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-4919
15945,31/12/2025,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-33370
15946,31/12/2025,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-24966

In [16]:
# Exportar resultados a csv
df_fact_mov_gastos.to_csv("PresupuestoGastos2025.csv", index=False)