In [3]:
# Importar librerias
import os
import pandas as pd
import numpy as np
from datetime import date

### 1. Tratamiento de datos de Ingresos

In [11]:
df_HechosVentasDiario = pd.read_csv('HechosVentasDiario.csv')
df_HechosVentasDiario[['Grupo']] =  "7"
df_HechosVentasDiario[['Tipo']] =  "Ingreso"
df_HechosVentasDiario = df_HechosVentasDiario[['Fecha', 'Ejercicio', 'Mes',  'Grupo', 'Tipo', 'CuentaContable', 'DescripcionCuenta', 'ClienteID', 'ProductoID', 'Importe']]
df_HechosVentasDiario

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,2023-01-01,2023,1,7,Ingreso,704000,Descuentos sobre ventas,29,11,-2743
1,2023-01-01,2023,1,7,Ingreso,705000,Prestaciones de servicios,46,6,12757
2,2023-01-01,2023,1,7,Ingreso,705000,Prestaciones de servicios,12,9,6585
3,2023-01-01,2023,1,7,Ingreso,704000,Descuentos sobre ventas,44,9,-1034
4,2023-01-01,2023,1,7,Ingreso,705000,Prestaciones de servicios,22,7,16624
...,...,...,...,...,...,...,...,...,...,...
10364,2025-12-31,2025,12,7,Ingreso,705000,Prestaciones de servicios,35,3,5294
10365,2025-12-31,2025,12,7,Ingreso,702000,Ventas de subproductos,26,7,24767
10366,2025-12-31,2025,12,7,Ingreso,700000,Ventas de mercaderías,40,8,6816
10367,2025-12-31,2025,12,7,Ingreso,705000,Prestaciones de servicios,24,2,21076
10368,2025-12-31,2025,12,7,Ingreso,700000,Ventas de mercaderías,2,1,17043

In [15]:
df_HechosOtrosIngresosNoOrdinariosDiario = pd.read_csv('HechosOtrosIngresosNoOrdinariosDiario.csv')
df_HechosOtrosIngresosNoOrdinariosDiario[['Grupo']] =  "7"
df_HechosOtrosIngresosNoOrdinariosDiario[['Tipo']] =  "Ingreso"
df_HechosOtrosIngresosNoOrdinariosDiario = df_HechosOtrosIngresosNoOrdinariosDiario[['Fecha', 'Ejercicio', 'Mes',  'Grupo', 'Tipo', 'CuentaContable', 'DescripcionCuenta', 'ClienteID', 'ProductoID', 'Importe']]
df_HechosOtrosIngresosNoOrdinariosDiario

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,2023-01-01,2023,1,7,Ingreso,770000,Ingresos extraordinarios,0,0,15496
1,2023-01-01,2023,1,7,Ingreso,770000,Ingresos extraordinarios,0,0,7346
2,2023-01-01,2023,1,7,Ingreso,746500,Subvenciones de capital transferidas a resultados,0,0,15129
3,2023-01-01,2023,1,7,Ingreso,760000,Ingresos financieros,0,0,548
4,2023-01-01,2023,1,7,Ingreso,770000,Ingresos extraordinarios,0,0,12142
...,...,...,...,...,...,...,...,...,...,...
5451,2025-12-31,2025,12,7,Ingreso,760000,Ingresos financieros,0,0,6528
5452,2025-12-31,2025,12,7,Ingreso,770000,Ingresos extraordinarios,0,0,15957
5453,2025-12-31,2025,12,7,Ingreso,746500,Subvenciones de capital transferidas a resultados,0,0,10610
5454,2025-12-31,2025,12,7,Ingreso,746500,Subvenciones de capital transferidas a resultados,0,0,14289
5455,2025-12-31,2025,12,7,Ingreso,760000,Ingresos financieros,0,0,4125

In [16]:
df_HechosOtrosIngresosExplotacionDiario = pd.read_csv('HechosOtrosIngresosExplotacionDiario.csv')
df_HechosOtrosIngresosExplotacionDiario[['Grupo']] =  "7"
df_HechosOtrosIngresosExplotacionDiario[['Tipo']] =  "Ingreso"
df_HechosOtrosIngresosExplotacionDiario = df_HechosOtrosIngresosExplotacionDiario[['Fecha', 'Ejercicio', 'Mes',  'Grupo', 'Tipo', 'CuentaContable', 'DescripcionCuenta', 'ClienteID', 'ProductoID', 'Importe']]
df_HechosOtrosIngresosExplotacionDiario

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,2023-01-01,2023,1,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,17948
1,2023-01-01,2023,1,7,Ingreso,740000,Subvenciones de explotación,0,0,22640
2,2023-01-01,2023,1,7,Ingreso,746000,Subvenciones para gastos de personal,0,0,3034
3,2023-01-01,2023,1,7,Ingreso,740000,Subvenciones de explotación,0,0,21685
4,2023-01-01,2023,1,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,11428
...,...,...,...,...,...,...,...,...,...,...
7132,2025-12-31,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,11273
7133,2025-12-31,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,7350
7134,2025-12-31,2025,12,7,Ingreso,746000,Subvenciones para gastos de personal,0,0,15632
7135,2025-12-31,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,11285
7136,2025-12-31,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,12534

In [18]:
df_fact_mov_ingresos =pd.concat([df_HechosVentasDiario,df_HechosOtrosIngresosNoOrdinariosDiario, df_HechosOtrosIngresosExplotacionDiario])
df_fact_mov_ingresos

,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,2023-01-01,2023,1,7,Ingreso,704000,Descuentos sobre ventas,29,11,-2743
1,2023-01-01,2023,1,7,Ingreso,705000,Prestaciones de servicios,46,6,12757
2,2023-01-01,2023,1,7,Ingreso,705000,Prestaciones de servicios,12,9,6585
3,2023-01-01,2023,1,7,Ingreso,704000,Descuentos sobre ventas,44,9,-1034
4,2023-01-01,2023,1,7,Ingreso,705000,Prestaciones de servicios,22,7,16624
...,...,...,...,...,...,...,...,...,...,...
7132,2025-12-31,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,11273
7133,2025-12-31,2025,12,7,Ingreso,794000,Reversión de provisiones para riesgos y gastos,0,0,7350
7134,2025-12-31,2025,12,7,Ingreso,746000,Subvenciones para gastos de personal,0,0,15632
7135,2025-12-31,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,11285
7136,2025-12-31,2025,12,7,Ingreso,792000,Reversión de provisiones de operaciones comerc...,0,0,12534

In [22]:
df_fact_mov_ingresos.to_csv("fact_mov_ingresos.csv", index=False)

### 2. Tratamiento de datos de Gastos

In [19]:
df_HechosGastosDiario = pd.read_csv('HechosGastosDiario.csv')
df_HechosGastosDiario

,Unnamed: 0,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,0,2023-01-01,2023,1,6,Gasto,625000,Primas de seguros,0,0,-12007
1,1,2023-01-01,2023,1,6,Gasto,606000,Descuentos sobre compras,0,0,613
2,2,2023-01-01,2023,1,6,Gasto,600000,Compras de mercaderías,0,0,-11246
3,3,2023-01-01,2023,1,6,Gasto,627000,"Publicidad, propaganda y relaciones públicas",0,0,-7027
4,4,2023-01-01,2023,1,6,Gasto,601000,Compras de materias primas,0,0,-15960
...,...,...,...,...,...,...,...,...,...,...,...
10378,10378,2025-12-31,2025,12,6,Gasto,601000,Compras de materias primas,0,0,-14032
10379,10379,2025-12-31,2025,12,6,Gasto,624000,Transportes,0,0,-6634
10380,10380,2025-12-31,2025,12,6,Gasto,627000,"Publicidad, propaganda y relaciones públicas",0,0,-1053
10381,10381,2025-12-31,2025,12,6,Gasto,628000,Suministros,0,0,-9017
10382,10382,2025-12-31,2025,12,6,Gasto,625000,Primas de seguros,0,0,-8213

In [20]:
df_HechosOtrosGastosDiario = pd.read_csv('HechosOtrosGastosDiario.csv')
df_HechosOtrosGastosDiario

,Unnamed: 0,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,0,2023-01-01,2023,1,6,Gasto,665000,Pérdidas por morosidad,0,0,-9469
1,1,2023-01-01,2023,1,6,Gasto,681000,Amortización del inmovilizado material,0,0,-5137
2,2,2023-01-01,2023,1,6,Gasto,660000,Gastos financieros,0,0,-19628
3,3,2023-01-02,2023,1,6,Gasto,660000,Gastos financieros,0,0,-7249
4,4,2023-01-02,2023,1,6,Gasto,660000,Gastos financieros,0,0,-25194
...,...,...,...,...,...,...,...,...,...,...,...
5559,5559,2025-12-31,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-19395
5560,5560,2025-12-31,2025,12,6,Gasto,660000,Gastos financieros,0,0,-12510
5561,5561,2025-12-31,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-4867
5562,5562,2025-12-31,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-32824
5563,5563,2025-12-31,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-24703

In [21]:
df_fact_mov_gastos =pd.concat([df_HechosGastosDiario,df_HechosOtrosGastosDiario])
df_fact_mov_gastos

,Unnamed: 0,Fecha,Ejercicio,Mes,Grupo,Tipo,CuentaContable,DescripcionCuenta,ClienteID,ProductoID,Importe
0,0,2023-01-01,2023,1,6,Gasto,625000,Primas de seguros,0,0,-12007
1,1,2023-01-01,2023,1,6,Gasto,606000,Descuentos sobre compras,0,0,613
2,2,2023-01-01,2023,1,6,Gasto,600000,Compras de mercaderías,0,0,-11246
3,3,2023-01-01,2023,1,6,Gasto,627000,"Publicidad, propaganda y relaciones públicas",0,0,-7027
4,4,2023-01-01,2023,1,6,Gasto,601000,Compras de materias primas,0,0,-15960
...,...,...,...,...,...,...,...,...,...,...,...
5559,5559,2025-12-31,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-19395
5560,5560,2025-12-31,2025,12,6,Gasto,660000,Gastos financieros,0,0,-12510
5561,5561,2025-12-31,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-4867
5562,5562,2025-12-31,2025,12,6,Gasto,665000,Pérdidas por morosidad,0,0,-32824
5563,5563,2025-12-31,2025,12,6,Gasto,681000,Amortización del inmovilizado material,0,0,-24703

In [23]:
df_fact_mov_gastos.to_csv("fact_mov_gastos.csv", index=False)